#!/bin/bash

# Install
git pull https://gist.github.com/a7f552e8b1fced1bc996.git

# Crystall structure
git pull https://gist.github.com/603c0d13bc7d3dc8148d.git

# Remote execution
git pull https://gist.github.com/d504ce067b99686e4ae8.git

# Elastic constants
git pull https://gist.github.com/5fb472070a272b61f75c.git

# Primitive unit cell
git pull https://gist.github.com/d68d81026eed03467d69.git

# Lattice dynamics
git pull https://gist.github.com/f3f37daa4cf1884f02ad.git

# Structural relaxation
git pull https://gist.github.com/f7b46f20640f3e2e7634.git

# Electronic Structure
git pull https://gist.github.com/99f18778525832746d48.git

# QHA
git pull https://gist.github.com/334b658cc8b3f6864c23.git
